type IconRule = { icon: string; pattern: RegExp };

const iconRules: IconRule[] = [
  { icon: "🐉", pattern: /龍|Dragon/i },
  { icon: "🐦", pattern: /伯德|Bird/i },
  { icon: "🐘", pattern: /大象|象開局|Elephant/i },
  { icon: "🦧", pattern: /猩猩|Orangutan/i },
  { icon: "🦔", pattern: /刺蝟|Hedgehog/i },
  { icon: "🦛", pattern: /河馬|Hippopotamus/i },
  { icon: "🐀", pattern: /鼠式|Rat Defense/i },
  { icon: "🐭", pattern: /旅鼠|Lemming/i },
  { icon: "🦘", pattern: /澳洲|袋鼠|Australian|Kangaroo/i },
  { icon: "🦁", pattern: /獅子|Lion/i },
  { icon: "🐍", pattern: /蛇|Snake/i },
  { icon: "🦕", pattern: /翼龍|Pterodactyl/i },
  { icon: "☁️", pattern: /雲中王|Bongcloud/i },
  { icon: "🎃", pattern: /萬聖節|Halloween/i },
  { icon: "🍖", pattern: /炸肝|Fried Liver/i },
  { icon: "🇪🇸", pattern: /西班牙|加泰隆尼亞|Ruy Lopez|Spanish|Catalan/i },
  { icon: "🇮🇹", pattern: /義大利|西西里|Italian|Sicilian/i },
  { icon: "🇫🇷", pattern: /法蘭西|French/i },
  { icon: "🇬🇧", pattern: /英式|英國|英格蘭|蘇格蘭|威爾斯|English Opening|English Defense|Scotch|Welsh/i },
  { icon: "🇳🇱", pattern: /荷蘭|Dutch/i },
  { icon: "🇮🇳", pattern: /印度|Indian/i },
  { icon: "🇩🇰", pattern: /丹麥|Danish/i },
  { icon: "🇵🇹", pattern: /葡萄牙|Portuguese/i },
  { icon: "🇵🇱", pattern: /波蘭|Polish/i },
  { icon: "🇱🇻", pattern: /拉脫維亞|Latvian/i },
  { icon: "🇭🇺", pattern: /匈牙利|Hungarian/i },
  { icon: "🇷🇺", pattern: /俄羅斯|Petrov|Russian/i },
  { icon: "🇨🇿", pattern: /捷克|Czech/i },
  { icon: "🇦🇹", pattern: /奧地利|Austrian/i },
  { icon: "🇨🇭", pattern: /瑞士|Swiss/i },
  { icon: "🇲🇽", pattern: /墨西哥|Mexican/i },
  { icon: "🇧🇷", pattern: /巴西|Brazilian/i },
  { icon: "🇦🇷", pattern: /阿根廷|Argentinian/i },
  { icon: "🇺🇦", pattern: /烏克蘭|Ukrainian/i },
  { icon: "🇸🇪", pattern: /斯堪地那維亞|Scandinavian/i },
  { icon: "🇮🇪", pattern: /愛爾蘭|Irish/i },
  { icon: "♞", pattern: /三馬|四馬|騎士|馬開局|Knight/i },
  { icon: "♝", pattern: /主教|象開局|Bishop/i },
  { icon: "♛", pattern: /后翼|后兵|女王|Queen/i },
  { icon: "♚", pattern: /王翼|王兵|King/i },
  { icon: "⚔️", pattern: /棄兵|Gambit/i },
  { icon: "⚡", pattern: /攻擊|Attack/i },
  { icon: "🛡️", pattern: /防禦|Defense/i },
  { icon: "♟️", pattern: /開局|Opening/i },
  { icon: "♜", pattern: /對局|Game/i },
];

export function openingIcon(titleZh: string, titleEn = "") {
  const title = `${titleZh} ${titleEn}`;
  return iconRules.find((rule) => rule.pattern.test(title))?.icon ?? "♟️";
}
